### ISSUE TITLE
Feature: load program from disk

### ISSUE THREAD

**Issue by yorickdewid** [felixangell/mac#3]
To extend the improved version it might be useful to load a programfile. This enables users to edit a program without the need to recompile. The step towards a bytecode encoded program stored on disk is very small then. If you check the encoded file for changes before executing would make it possible to optimize the code. At that point you've almost implemented a full stack virtual machine.

Just some thoughts...

**Comment by felixangell** [comment]
Do you mean like hot swapping the code? I'm confused

**Comment by yorickdewid** [comment]
To load the program from a (encoded) file so that the vm really 'runs' the code instead of the hardcoding a predefined structure. Much like interpreter vm's such as CPython do.

**Comment by felixangell** [comment]
Oh wait sorry, I thought this was for Alloy and not mac so I was really confused. Yeah you could do file IO, it should be relatively easy. I would do it, but I don't want to deviate too much from the article that this repository is for.

**Comment by yorickdewid** [comment]
Say the thing, read the article (excellent by the way :+1: ) and I kind of was expecting you'd want to stick to the blog post. Anyway, I'm planning on doing something myself later this year including a tokenizer and the parse/AST story. Something Python based, but with a small footprint.

**Comment by felixangell** [comment]
Thanks! 11/10 would write another article again, Matz -- the guy who created Ruby -- tweeted my article!!!!!!!!!!!!!!!!! :astonished:  And yeah, sounds awesome, virtual machines are great. They're what got me into more lower level concepts of computers like compilers, etc. I'll check it out when it's up :)

**Comment by felixangell** [comment]
Might do this later today on another branch since I'm kinda bored :)

**Comment by yorickdewid** [comment]
I'll check it out then :+1:

**Comment by felixangell** [comment]
@yorickdewid :grinning: I'll be back in around 2 hours and I'll probably work on it then :)

**Comment by felixangell** [comment]
@yorickdewid Done :) Mac improved now reads a binary file from the disk.

**Comment by yorickdewid** [comment]
Seems to be working, nice. Though it looks like you don't allocate enough for the instructions array.
Anyway you should add some cleanup procedures to free the blocks and close the descriptor.

Looks pretty good, next step is to generate these .mac files based on user input? :)

**Comment by felixangell** [comment]
@yorickdewid It allocates more space when necessary, and the instructions buffer is increased exponentially. And good catch on the cleanup, forgot about that.
