### ISSUE TITLE
I think I caught a small bug

### ISSUE THREAD

**Issue by aaron-elkins** [felixangell/mac#6]
at line 187 in this file mac-improved/mac.c, it was:

```
registers[IP + 1] = instructions[IP + 3];
```

I think it should be:

```
registers[IP] = instructions[IP + 3];
break;
```

Cause it should change current instruction pointer to 3rd arguments of IF instruction if the test is true, right?

**Comment by felixangell** [comment]
Ohh, good catch there. Yeah it should set the instruction pointers value to whatever that address is.
